### ISSUE TITLE
How to work with it?

### ISSUE THREAD

**Issue by aabsz** [kaasa-solution/Kaasa.Mds.Android#1]
Hi,

I have no knowledge of Android and IOS. I am going to use 5 Movesense sensors in a project. I know that I have to install an app on my phone with the .apk format. Can you please help me with how to use this repository to do that?

**Comment by abduelhamit** [comment]
Hello,

This project is a library designed for MAUI app developers, not a finished app. To use it, you need some knowledge about developing apps in MAUI. Teaching that is out of the scope of an issue.

To learn more about developing in MAUI, visit [the MAUI documentation](https://learn.microsoft.com/dotnet/maui/), watch [the short video series .NET MAUI for Beginners](https://www.youtube.com/playlist?list=PLdo4fOcmZ0oUBAdL2NwBpDs32zwGqb9DY), or watch [the full course by James Montemagno](https://www.youtube.com/watch?v=DuNLR_NJv8U).
